baseURL = "https://sheepdog.dev/"
title = "Urbano Sheepdog"
enableRobotsTXT = true
enableGitInfo = false
hasCJKLanguage = true
defaultContentLanguage = "en"
enableInlineShortcodes = true

[[module.imports]]
path = "github.com/imfing/hextra"

[outputs]
home = [ "HTML" ]
page = [ "HTML" ]
section = [ "HTML", "RSS" ]

[languages.en]
languageName = "English"
weight = 1
title = "Urbano Sheepdog"

[languages.pt]
languageName = "Português Brasileiro"
languageCode = "pt-br"
languageDirection = "ltr"
weight = 2
title = "Urbano Sheepdog"

[markup.highlight]
noClasses = false

[markup.goldmark.renderer]
unsafe = true

[[menu.main]]
identifier = "documentation"
name = "Documentation"
pageRef = "/docs"
weight = 1
[[menu.main]]
identifier = "posts"
name = "Posts"
pageRef = "/posts"
weight = 2

[[menu.main]]
identifier = "papers"
name = "Papers"
pageRef = "/papers"
weight = 3

[[menu.main]]
identifier = "about"
name = "About"
pageRef = "/about"
weight = 4

[[menu.main]]
identifier = "manifesto"
name = "Manifesto"
pageRef = "/manifesto"
weight = 5

[[menu.main]]
name = "Search"
weight = 6

  [menu.main.params]
  type = "search"

[[menu.main]]
name = "GitHub"
weight = 7
url = "https://github.com/urbanosheepdog"

  [menu.main.params]
  icon = "github"

[[menu.main]]
name = "LinkedIn"
weight = 8
url = "https://linkedin.com/company/urbanosheepdog"

  [menu.main.params]
  icon = "linkedin"

[[menu.sidebar]]
identifier = "more"
name = "More"
weight = 1

  [menu.sidebar.params]
  type = "separator"

[[menu.sidebar]]
identifier = "about"
name = "About"
pageRef = "/about"
weight = 2

[params]
description = "smart defense systems"
displayUpdatedDate = true
dateFormat = "January 2, 2006"

  [params.navbar]
  displayTitle = true
  displayLogo = true
  width = "wide"

    [params.navbar.logo]
    path = "images/logo.png"
    dark = "images/logo.png"
    link =  "/"
    width = "50"
    height = "50"


  [params.page]
  width = "normal"

  [params.theme]
  default = "system"
  displayToggle = true

  [params.footer]
  enable = true
  displayCopyright = false
  displayPoweredBy = false
  width = "wide"

  [params.search]
  enable = true
  type = "flexsearch"

    [params.search.flexsearch]
    index = "content"
    tokenize = "forward"

  [params.editURL]
  enable = false
  base = "https://github.com/imfing/hextra/edit/main/exampleSite/content"

[params.blog.list]
displayTags = true
sortBy = "date"
sortOrder = "desc"

[params.blog.article]
displayPagination = true

  [params.toc]
  displayTags = true

[params.highlight.copy]
enable = true
display = "hover"

  [params.comments]
  enable = false
  type = "giscus"

    [params.comments.giscus]
    repo = "imfing/hextra"
    repoId = "R_kgDOJ9fJag"
    category = "General"
    categoryId = "DIC_kwDOJ9fJas4CY7gW"
